### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-bridge-sol#33]
- [x] naming conventions，lock, unlock, register, etc
- [x] ~~use oracle to get ERC20 token's metadata, include name, symbol, and decimal, must be string, string, uint8 types~~
- [x] backing address needs to be restricted in a whitelist
- [x] delete delegator to simplify register protocol
- [x] precompile contract address list (@AsceticBear)
- [x] don't burn user's token directly, instead, transfer first
